#!maicro
#---
# title: AI Task Setup
# intent: Configure the Drivers License processing task and related Drivers License GraphQL type.
# description: This script uses the required steps to configure the AI task and type and leave them in place, whereas the test version would cleanup and delete these components.
# difficulty: beginner
# estimated_time: 3m
# tags:
#   - ai
#   - config
#   - tasks
#   - graphql
#---

###> REGISTER GRAPHQL TYPE
#{
# ## Create DriversLicense Type
# Creates the user-defined GraphQL type that the AI task references.
#}
mutation RegisterDriversLicenseType {
  DbExecute(path: "scripts/courses/01000.ai_tasks/03.setup_drivers_license_type.gql") {
    success
    message
    result
  }
}





