#!maicro
#---
# title: AI Task Test
# intent: Test the setup and teardown of AI Tasks and related GraphQL types.
# description: Create, query, update and delete the AI task to provide an end to end test scenario.
# difficulty: beginner
# estimated_time: 3m
# tags:
#   - ai
#   - config
#   - tasks
#   - graphql
#---

###> CONFIGURE DOCUMENT TYPE
#{
# ## Configure Drivers License Analysis
# Creates the `DriversLicense` GraphQL type and the `drivers_license` document
# type. The document type delegates extraction to the reusable
# `json_extraction` AI task.
#}
mutation ConfigureDriversLicenseDocumentType {
  DbExecute(path: "scripts/courses/01000.ai_tasks/03.setup_drivers_license_type.gql") {
    success
    message
    result
  }
}
