#!maicro
#---
# title: List And Get Drivers License Task
# description: List AI tasks and fetch the drivers license task definition.
# difficulty: beginner
# estimated_time: 2m
# tags:
#   - ai
#   - tasks
#---
###> LIST AND FETCH AI TASKS
query ListAndFetchDriversLicenseTask {
  AiTasks {
    key
    label
    description
    model
    sources
    prompt
    output_mode
    graphql_type
    missing_value
  }

  AiTask(key: "drivers_license") {
    key
    label
    description
    model
    sources
    prompt
    output_mode
    graphql_type
    missing_value
  }
}
