#!maicro
#---
# title: Delete Drivers License Task
# description: Remove the drivers license AI task and related type.
# difficulty: beginner
# estimated_time: 2m
# tags:
#   - ai
#   - cleanup
#---
###> DELETE AI TASK
mutation DeleteDriversLicenseTask {
  AiTaskDelete(key: "drivers_license") {
    success
    key
    message
  }
}

###> DELETE DRIVERLICENSE TYPE
mutation DeleteType {
  DeleteType(name: "DriverLicense"){
    success
  }
}