###> CLEAN UP TAXONOMY ENUMS AND TYPES (COMPACT)
mutation CleanupTaxonomy {
  DeleteTypes(
    failIfNotFound: false
    enums: ["DocumentPurpose", "DocumentType", "DVACardColour"]
    types: [
      "Passport"
      "DriversLicense"
      "DVACard"
      "PensionCard"
      "MedicareCard"
      "GPHealthSummary"
      "CurrentMedicationList"
      "AlliedHealthReports"
      "HospitalDischargeSummary"
      "AssessmentOutcomeLetter"
      "AdvanceCareDirective"
      "BehaviourSupportPlan"
      "MyAgedCareSupportPlan"
      "SupportAtHomeCarePlan"
      "FinancialAuthorityDocuments"
      "ResidentialMeansAssessmentOutcome"
      "SA457"
      "SA485"
      "EnduringPowerOfAttorney"
      "GuardianshipOrders"
    ]
  ) {
    success
    message
  }

  DbReload
}