#!maicro
#---
# title: Fetch Authors and Store in Memory
# description: Queries all authors from the database and stores the result in persistent memory.
#---

###> FETCH AUTHORS
query FetchAuthors {
  authors {
    id
    name
    bio
  }
}
             
###> STORE IN MEMORY
mutation RememberAuthors {
  RememberAuthors:Remember(
    id: "authors"
    json: "{{@@.authors}}"
  )
}
             
###> REMEMBER READERS
mutation RememberReaders {
  RememberReaders:Remember(
    id: "readers"
    json: "{{@?.readers}}"
  )
}
             
###> REMEMBER PREMIUM READERS
mutation RememberPremiumReaders {
  RememberPremiumReaders:Remember(
    id: "premium_readers"
    json: "{{@?.readers[membership_level eq \"premium\"]}}"
  )
}
             
###> RECALL PREMIUM READERS
query RecallPremiumReaders {
  StoredPremiumReaders:Recall(id: "premium_readers")
}
             
###> RECALL FIRST PREMIUM READER NAME
query RecallFirstPremiumReaderName {
  FirstPremiumReaderName: Recall(
    id: "premium_readers"
    path: "0.username"
  )
}
             
###> ASSERT FIRST STORED READER NAME
query AssertFirstStoredReaderName {
  firstReaderIsAliceJohnson: Assert(
    actual: "{{@#.readers.0.username}}"
    op: "eq"
    expected: "pattyb"
  ) {
    success
    message
  }
}